version: '3.8'

# service define
services:
# main server (on replicate mode)
 main:
  image: 2mukee/mh_main_deploy
  ports:
   - 443:17260
  environment:
   - TZ=Asia/Seoul
  deploy:
   mode: replicated
   replicas: 5
   update_config:
    parallelism: 5
    delay: 10s
    order: start-first
    failure_action: rollback

# database server
 db:
  image: 2mukee/mh_db_deploy
  environment:
   - TZ=Asia/Seoul
  volumes:
   - /home/mh-dev/data:/data/db
  environment:
   - TZ=Asia/Seoul

# api server
 api:
  image: 2mukee/mh_api_deploy
  environment:
   - TZ=Asia/Seoul
  env_file:
   - ./api/mh.env
  deploy:
   update_config:
    delay: 10s
    order: start-first
    failure_action: rollback