version: '3.8'

services:
 main:
  image: 2mukee/mh_main_deploy:latest
  ports:
   - 443:17260
  depends_on:
   - db
  environment:
   - TZ=Asia/Seoul
  deploy:
   mode: replicated
   replicas: 5
   update_config:
    parallelism: 5
    delay: 10s
    order: stop-first
    failure_action: rollback

 db:
  image: 2mukee/mh_db_deploy:latest
  volumes:
   - /home/mh-dev/data:/data/db
  environment:
   - TZ=Asia/Seoul

 api:
  image: 2mukee/mh_api_deploy:latest
  depends_on:
   - main
  environment:
   - TZ=Asia/Seoul
  env_file:
   - ./api/mh.env
  deploy:
   mode: replicated
   replicas: 5
   update_config:
    parallelism: 5
    delay: 10s
    order: stop-first
    failure_action: rollback